### ISSUE TITLE
Android passwords changed? Now different than Web and Desktop Java

### ISSUE THREAD

**Issue by e-geist** [Lyndir/MasterPassword#117]
Hi,

I just got a new phone today and downloaded the Android version of MasterPassword from https://ssl.masterpasswordapp.com/ . 

I tried generating some passwords, but they are different than they used to be and different than the ones I get from the Web generator and the Desktop Java Android version.

The phone is a chinese LeEco LeMax2.

Did the algorithm change, is it a bug or did I do something wrong?

Thanks in advance.

**Comment by lhunath** [comment]
Dupe of #127 ?

**Comment by diabolusss** [comment]
Could someone, please, add to git or mail me latest MPW version of android app? I have the same issue, but could find only 2.1v application for android.
