### ISSUE TITLE
Password labels difficult to read-not enough contrast

### ISSUE THREAD

**Issue by aajoyce** [Lyndir/MasterPassword#123]
I'm finding it very difficult to read the labels for the passwords when I'm using the program on my iPhone. There just doesn't seem to be enough contrast with the black background and the grey letters. Perhaps white letters would show up better. Sometimes I have to guess that I’m on the right password.

**Comment by lhunath** [comment]
Fixed in 0a1f215a1ac1170096099ebb9e6ffa7a98d15b24
