### ISSUE TITLE
Export table to take full use of spreadsheet

### ISSUE THREAD

**Issue by ghost** [Lyndir/MasterPassword#124]
When I export a export a list of sites, whether secure or revealing passwords, it would help a lot to have the table formatted so that each item has it's own cell. Currently, the Last Used, Times Used, Password Type, and Login Name all share the same cell in a row of the table. I've spent considerable time reformatting the table so that the information is more easily manipulated. Plus, it would be very handy to have the password type be divided so that I could tell which iteration of password was being applied to a particular site. Also, if each table column were void of spaces, it would help tremendously in trying to sort the table. Trying to take out all those extra spaces is a real bear! Maybe exporting as a comma delimited file would work to accomplish this. 
Why am I requesting this? Because I want to save a copy of the exported sites in a password protected file that I can access if necessary as a hardcopy for my own use. I've changed the way I do passwords since using MasterPassword, but I am still more comfortable having a backup copy that I can access should my computer be stolen or should something catastrophic happen. It's also helpful to be able to sort the entire table to see if there are duplicate sites in the file.

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
