### ISSUE TITLE
MP-73 Native Java scrypt library fails on some Android device architectures.

### ISSUE THREAD

**Issue by lhunath** [Lyndir/MasterPassword#127]
https://project.lyndir.com/youtrack/issue/MP-73

The native library currently bundled with the Android app produces incorrect results on certain architectures.

**Comment by lhunath** [comment]
Fixed in 2.4.1 by removing libscrypt's arm64 library, causing it to revert to 32-bit compatibility mode.

**Comment by mpmont** [comment]
Hi there, I'm having this issue on my phone. Current phone I have is a Xiaomi Redmi 4 running rom miui version 8.5.4.0 and Android version 6.0.1
