### ISSUE TITLE
MP-7 Consider expiring the password from the pasteboard.

### ISSUE THREAD

**Issue by lhunath** [Lyndir/MasterPassword#132]
https://project.lyndir.com/youtrack/issue/MP-7

Since passwords are transferred via the pasteboard, it might be nice if we can expire them either after use or after a time-out.

**Comment by toonn** [comment]
#130 is similar.

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
