### ISSUE TITLE
Support for older OSX versions? 

### ISSUE THREAD

**Issue by seb45tian** [Lyndir/MasterPassword#141]
Hi,
I just wanted to know if there is anything preventing the macOS App to run on the older OSX 10.9 or 10.10 releases? I know there is the Java version, but it would be nice to have a native app working, also on older systems.

Thx for the hard work!

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
