### ISSUE TITLE
OS X app: Logged-in state flashes before asking for password

### ISSUE THREAD

**Issue by mikemonteith** [Lyndir/MasterPassword#142]
When I open the OS X app: if I have been "logged in" previously, my list of passwords is briefly flashed on screen before going to the master password entry screen.

I have only noticed this after upgrading to OS X v10.11, I assume this is some sort of mechanism in OS X that shows the app's last view on opening until the app renders it's first frame (?).

I don't know much about how OS X works but hopefully will look into this further if I get a chance.

**Comment by lhunath** [comment]
Does this still happen with the current version (2.5.2)?
https://ssl.masterpasswordapp.com/masterpassword-mac.zip or the Mac App Store.

**Comment by mikemonteith** [comment]
This issue seems to be fixed, but I haven't upgraded to 2.5.2 yet 😕 
I have upgraded my OS though, now running v10.12.3 so maybe it's only a problem for v10.11

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
