### ISSUE TITLE
No good way of changing your master password without changing your name (java app)

### ISSUE THREAD

**Issue by fallerOfFalls** [Lyndir/MasterPassword#143]
If you need to change your master password (and therefore all passwords that were generated with it) you need to be able to access both sets of passwords (the first in order to get your old password, and the second in order to generate the new one). But you can't create a separate user with the same name, so how are you supposed to do that?

**Comment by lhunath** [comment]
The process isn't really easily doable with the Java Desktop app.  It would be easy with the CLI, with the Mac and iOS apps you can generate an export which functions as a list of old and new passwords to go through.  You could use the Java Desktop app in incognito mode.

**Comment by fallerOfFalls** [comment]
Oh yeah, I'd forgotten about incognito mode, thanks.

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
