### ISSUE TITLE
No installation instructions or requirements file for Masterpassword CLI

### ISSUE THREAD

**Issue by crypdick** [Lyndir/MasterPassword#144]
I think this is a wonderful concept for password management. Every time I reinstall Linux it's a nightmare getting MPW to work again, though. The main website just links to the CLI archive. No ReadMe or Requirements file in the archive, no build instructions on the website or on Github. I'm stuck as in dependency hell Google-ing one terminal error after another.

**Comment by lhunath** [comment]
Feel free to paste the errors here.  There shouldn't be any.  Essentially, if your distribution doesn't provide an "mpw" package, just clone the repo, head over to `MasterPassword/C` and run `./build` and `./install`

**Comment by isomerase** [comment]
No `mpw` package in Ubuntu or Linux Mint. Here's what I've gone through so far on a fresh install of Linux Mint.

At first it fails and tells me to get `automake` and `autoconf`. I do that, try again:

```
lib/scryptenc/scryptenc.c:38:25: fatal error: openssl/aes.h: No such file or directory
compilation terminated.
Makefile:524: recipe for target 'scrypt-scryptenc.o' failed
make[1]: *** [scrypt-scryptenc.o] Error 1
make[1]: Leaving directory '/home/pepe/Apps/masterpassword-cli/lib/scrypt'
Makefile:338: recipe for target 'all' failed
make: *** [all] Error 2
```
Google tells me to get `libssl-dev`. Then:

```
In file included from mpw-tests-util.c:15:0:
mpw-tests-util.h:9:27: fatal error: libxml/parser.h: No such file or directory
compilation terminated.
```

Google tells me to get `libxml2` and `libxml2-dev`. Try again:

```
Building target: mpw-tests...
mpw-tests-util.o: In function `mpw_xmlTestCaseNode':
mpw-tests-util.c:(.text+0xc4): undefined reference to `xmlStrcmp'
mpw-tests-util.c:(.text+0x109): undefined reference to `xmlStrcmp'
mpw-tests-util.c:(.text+0x1a8): undefined reference to `xmlStrcmp'
mpw-tests-util.c:(.text+0x1ba): undefined reference to `xmlFree'
mpw-tests-util.c:(.text+0x1d0): undefined reference to `xmlFree'
mpw-tests-util.o: In function `mpw_xmlTestCaseString':
mpw-tests-util.c:(.text+0x270): undefined reference to `xmlNodeGetContent'
mpw-tests-util.o: In function `mpw_xmlTestCaseInteger':
mpw-tests-util.c:(.text+0x2af): undefined reference to `xmlFree'
/tmp/ccnb9W7G.o: In function `main':
mpw-tests.c:(.text+0x25): undefined reference to `xmlParseFile'
mpw-tests.c:(.text+0x2d): undefined reference to `xmlDocGetRootElement'
mpw-tests.c:(.text+0x67): undefined reference to `xmlStrcmp'
mpw-tests.c:(.text+0x24a): undefined reference to `xmlStrcmp'
mpw-tests.c:(.text+0x2a6): undefined reference to `xmlFree'
mpw-tests.c:(.text+0x2b6): undefined reference to `xmlFree'
mpw-tests.c:(.text+0x2c6): undefined reference to `xmlFree'
mpw-tests.c:(.text+0x2d6): undefined reference to `xmlFree'
mpw-tests.c:(.text+0x2e6): undefined reference to `xmlFree'
/tmp/ccnb9W7G.o:mpw-tests.c:(.text+0x2f6): more undefined references to `xmlFree' follow
collect2: error: ld returned 1 exit status
```
Here I get stuck. I see it installed at `/usr/include/libxml2` and the build file appears to check in that directory.  

If you tell me the rest of the prereqs I'm happy to submit a PR with install instructions for Ubuntu.

**Comment by isomerase** [comment]
Ok, so I tried deleting the files I got from http://masterpasswordapp.com/ and tried getting everything directly from the repo. When I build, different errors:

```
Building target: mpw...
mpw-types.c:15:20: fatal error: curses.h: No such file or directory
compilation terminated.
```

Google says get `libncurses5-dev libncursesw5-dev`. Success!
