### ISSUE TITLE
Selected User is not saved on macOSX 10.12.1 (Sierra)

### ISSUE THREAD

**Issue by jackowacko83** [Lyndir/MasterPassword#146]
I installed mpa on my MacBookPro with MacOSX Sierra. After creating the user, the app won't remember the last chosen user. When I hit the shortcut (ctrl+cmd+p) I get prompted that no user is selected. After selecting a user through the tray icon, the shortcut works, but only if I haven't focused on another application. After focusing on another application, the user is no longer selected and I get the prompt again.
If there is some kind of workaround like manually setting the default user in a file, I would appreciate if anyone could tell me.

**Comment by jinwoo** [comment]
+1. I've been having this problem even before Sierra and it has been driving me crazy.

**Comment by floq-design** [comment]
+1 El Capitan 10.11.6 problem exists

**Comment by lhunath** [comment]
Dupes #126
