### ISSUE TITLE
I don't know in what website I can use the encrypted password 

### ISSUE THREAD

**Issue by fcode520** [Lyndir/MasterPassword#147]
I don't know in what website I use the MasterPassword?
I want to record what I use all of the WebSite, how should I do?

**Comment by tlze** [comment]
https://js.masterpasswordapp.com/

**Comment by lhunath** [comment]
The js.masterpasswordapp.com website does not support storing encrypted passwords. It is a stateless MasterPassword password encoder.

**Comment by lhunath** [comment]
This is not an issue.
