### ISSUE TITLE
OS X app serious performance issue when using similar site names

### ISSUE THREAD

**Issue by bedeabza** [Lyndir/MasterPassword#148]
I use a particular naming convention for my sites that causes site names to be fairly similar and observed that the password generation starts to get really really slow and blocks the UI when using the same first part for the site name.

Examples of site names generated by my naming convention:

- test.site.com
- test.site2.com
- test.site3.com
...
- test.site20.com

After having about 10 sites starting with "test.site" password generation takes a long time, while if you get that number to around 20, it's unusable.

Here is a video of how to reproduce this behaviour: [http://screencast.com/t/JhlUfKHLcU](http://screencast.com/t/JhlUfKHLcU)

Because password generation is done in real time while typing this becomes a serious issue, especially when having site names that have a lot of characters.

**Comment by lhunath** [comment]
05391d89
