### ISSUE TITLE
Update the time in the FAQ

### ISSUE THREAD

**Issue by mylainos** [Lyndir/MasterPassword#151]
In the FAQ the number of hashes per second is based on an GPU card. But Bitcoin use the same hash algorithm as MasterPassword. And Bitcoin miners use [ASIC (Application-specific integrated circuit)](https://en.wikipedia.org/wiki/Application-specific_integrated_circuit). These can do only one thing, extremely fast, and for less power cost than a CPU or GPU. ASICs used for bitcoin hash the header of blocks with hmac-sha256.

It's possible to [buy an ASIC](https://shop.bitmain.com/productDetail.htm?pid=00020161116015622659M8nhWeAc06B1) which can calculate 11T hashes/s for 1200$ (without the power cost). Comparing with the 1G hashes/s of the GPU, you have a factor of 10000. The times in the comparison needs an update.

Plus I think it's best to show the time to hash 1/2 of all passwords because you will be very lucky if your password is the last one to be hashed.

**Comment by lhunath** [comment]
It certainly would be interesting to research the most accurate way of getting reliable representative values.  I'm open to suggestions and proposals.

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
