### ISSUE TITLE
Create an Organisation and separate the app in differents repository

### ISSUE THREAD

**Issue by mylainos** [Lyndir/MasterPassword#152]
I think every applications should be in its own repository. It would be clearer and the management of issues easier.
And an Organisation will be a good way to keep everything accessible (when a name will be chosen).

**Comment by Kcchouette** [comment]
I agree with @Mylainos, is it possible to separe each project of MasterPassword (one for web-js, one for java apps, one for android apps, etc) and put them in this repositorie as gitmodules?

I need to clone all the repo to only use the [web-js](https://github.com/Lyndir/MasterPassword/tree/master/platform-independent/web-js) version!

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
