### ISSUE TITLE
Create a core lib and call it with FFI

### ISSUE THREAD

**Issue by Mylainos** [Lyndir/MasterPassword#153]
This will reduce the code redundancy, be easier to maintain and there will be one standard implementation so everyone can reuse it for uses cases we haven't thought.

Maybe Foreign Function Interface will add overhead but the pros outpace the cons.

**Comment by lhunath** [comment]
This is essentially what the C code is:
https://github.com/Lyndir/MasterPassword/tree/master/MasterPassword/C

The iOS and Mac apps have recently been modified to purge their own implementation of mpw and implement the C code instead.

Java currently still implements the algorithm natively, but the C implementation is essentially the "reference" implementation.

**Comment by Mylainos** [comment]
Cool.
I've just look to the c and java code.

**Comment by Mylainos** [comment]
Do you want to use JNI or SWIG so the only implementation will be the C one?

**Comment by lhunath** [comment]
I would certainly consider such a contribution, but I haven't the time resources to implement this myself.

**Comment by Mylainos** [comment]
Ok, I will do it.

**Comment by lhunath** [comment]
Closing this for now as it's not really a priority.  If such a contribution is made, it can be re-opened or a pull request made.
