### ISSUE TITLE
Licensing headers?

### ISSUE THREAD

**Issue by donaldr3** [Lyndir/MasterPassword#154]
I was trying to verify that the work is GPLv3 or later, and found that many files do not have licensing headers, or simply claim all rights reserved. You can see how to make sure files from your project have proper headers [here](https://www.gnu.org/licenses/gpl-howto.en.html).

**Comment by Binero** [comment]
I would like to add that having a license on every source file is not required at all and a license file in the root of the project suffices legally. 

The only reason you'd add a license header to all of your files if not all of them have the same license (e.g. when you are using some files from other open source projects).

**Comment by lhunath** [comment]
a363a8a71572b0731266d5ea0446f05744e6417a e39062a32d923322da1205ee6bc2613b4ec33d3f
