### ISSUE TITLE
Allow Additional Fields

### ISSUE THREAD

**Issue by Binero** [Lyndir/MasterPassword#155]
Currently, it's hard to have multiple accounts on MasterPassword. If you for instance have multiple Google / GMail accounts, you cannot simply use "google.com" anymore as website name. 

Maybe we should allow people to add additional fields like a username?

**Comment by panther2** [comment]
You could use your account name as site name in this case (so `name@gmail.com`).

**Comment by lhunath** [comment]
[name]@[site] is the recommended convention, yes, even for non-email accounts; eg. [me]@twitter.com.

I have been considering implementing this convention in the UI directly, but am not sure yet.  I would want it to remain 100% transparent that the name and site are not distinct fields but together form the "site name".

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
