### ISSUE TITLE
Feature Request: Custom Password Pattern

### ISSUE THREAD

**Issue by tlewis3348** [Lyndir/MasterPassword#159]
Sometimes sites will unfortunately have restrictions on the type of characters that can be used, but not on the length.  I would very much like to create custom patterns that include the characters they allow, but don't include the characters they don't allow and have a longer length than just a handful of characters.  Right now, for example, a "Long Password" can have the pattern `CvcvnoCvcvCvcv` (or variations on that theme) where `o` represents any of the following characters: `@&%?,=[]_:-+*$#!'^~;()/.`.  However, some sites may allow half of those characters, but disallow the other half.  If I could create my own set of characters as well as my own template pattern, I would be able to have a stronger password for those sites, but as it is now, when it comes to special characters, a site has to either accept all of them or none of them.

Additionally, if the site limits you to just alpha-numeric characters, you're only option is to use an 8 character long "Basic Password", when a longer one could potentially be used.

**Comment by lhunath** [comment]
See #130
