### ISSUE TITLE
Compile problems due to "Scrypt" dependency

### ISSUE THREAD

**Issue by kirawrath** [Lyndir/MasterPassword#160]
Hi,

Apparently someone moved a folder in the Scrypt repository so now the build script no longer works:

```
./build
Will build targets: mpw mpw-bench mpw-tests...

Checking dependency: scrypt...
~/Downloads/mpw/lib/scrypt ~/Downloads/mpw

Fetching: scrypt, using git-svn...
Initialized empty Git repository in /home/loreto/Downloads/mpw/lib/scrypt/.git/
Can't create session: Unable to connect to a repository at URL 'http://scrypt.googlecode.com/svn': '/svn' path not found at /usr/share/perl5/vendor_perl/Git/SVN.pm line 310.
```

Oh, this is the latest linux CLI version btw. I'm using a up-to-date Arch Linux machine.

**Comment by lhunath** [comment]
Is this still a problem on master?

**Comment by CarlosEvo** [comment]
It's still a problem, although I am using Arch Linux in WSL.

**Comment by lhunath** [comment]
Do you have local changes?  It seems to me like `MasterPassword/core/c/lib/scrypt/.source` has lost the `git=` source.

**Comment by lhunath** [comment]
Oh, sorry, you're talking about the download from the website.  Yes, this one is outdated, I just noticed.  Please check out master from the repository instead.

**Comment by lhunath** [comment]
Should be fixed now that the CLI tarball has been updated.
