### ISSUE TITLE
[Question] Can I keep the website's password after changing the master password?

### ISSUE THREAD

**Issue by fenghse** [Lyndir/MasterPassword#161]
Two questions about the feature:
1. Can I keep the website's password after changing the master password?
2. Can I assign a password for specific website?

Thx.

**Comment by lhunath** [comment]
This is a bug reporter, not a help forum.  Please see http://help.masterpasswordapp.com/ for the latter.

1. No.
2. No.

That said, some of the Master Password apps have a hybrid mode that implements a fault-like functionality which supports 2.  Regardless, it is recommended that you use generated passwords for all intents and purposes.
