### ISSUE TITLE
Feature-wish: User define password length and composition

### ISSUE THREAD

**Issue by CriJ** [Lyndir/MasterPassword#162]
The more I use MP, the more I get the problem, that the generated passwords are not usable for the desired service. How's about adding a possibility for user defined password complexity?

For example some services restirct the passoword complexity like this:
- password must be exact 5 character long and must contain one special character, but not all are allowed (not [,], etc.)
- password must be min. 10 characters long, and I do not want to use the full long name with 16 characters
 
An idea may be to define the wanted complexity via regular expressions.

**Comment by lhunath** [comment]
See #130
