### ISSUE TITLE
Set default password type for user on macOS.

### ISSUE THREAD

**Issue by lhunath** [Lyndir/MasterPassword#167]
macOS does not yet support setting the user's default site password type.

**Comment by lhunath** [comment]
In d9bd604436815bacfe448778acf13e5b8c317944 this might be achieved by exporting the user's settings into an mpsites file, modifying the file's `Default Type` header and importing it again.

**Comment by Mattiaslndstrm** [comment]
I'm very interested in this. It's a bit cumbersome to have to set the password type for each new site.

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
