### ISSUE TITLE
Verify master password entered correctly

### ISSUE THREAD

**Issue by lnxworx** [Lyndir/MasterPassword#169]
I have used the CLI, Android App and the Java app.  There is only a single field/prompt for the  masterpassword without any validation that the password was typed correctly.  I think its crucial that there be a check to see if the masterpassword was typed correctly since a single digit foobar could wreck the whole deal.

Thanks for an outstanding application!

**Comment by lhunath** [comment]
Where would you like this check?  Are you referring to the Android application?

Note that the CLI and the Java application both display an "identicon" to provide this type of verification.  If the identicon is the one you expect, you've entered the right name & master password.  If the CLI gives you a password but an identicon you didn't expect, you probably typo'ed your name or master password.

The Java application also supports storing your user and key ID in an mpsites file, and checks the entered master password against it when logging back in later - it should detect typo's and error during the login step (assuming you aren't using the incognito mode).

The Android app doesn't currently provide support for either of these features.

**Comment by lnxworx** [comment]
Maarten:

Thanks for the quick reply.

I now understand how the CLI works.  I am used to getting a second password
prompt to verify the password entry.  It would be nice to have the
identicon functionality in the Android application as well, but I also
understand that it's a beta and not fully baked yet.

Are there any plans to integrate an mpsites file into all of the methods of
password generation?  I am trying to standardize on domain.topleveldomain
but I have so many logins (some that I only use rarely) that without a list
I would likely forget they even exist.  Right now I am just tracking them
in a spreadsheet that I store on encfs that is kept in dropbox.

Thanks again for the excellent work.  At first I thought it would be
difficult to move from keepassx to masterpassword, but the transition
(though time consuming) has been very smooth and I like that I can
obfuscate logins, answers and passwords and retrieving them isn't a huge
pain in the ass.

Cheers,

Chris

On Mon, Apr 24, 2017 at 7:46 PM, Maarten Billemont <notifications@github.com

**Comment by lhunath** [comment]
WRT your question about the mpsites file, see #164

**Comment by haroon-ali** [comment]
Yes, "identicon" is the really missing feature on Android.

**Comment by chsm** [comment]
FWIW, I just enter "test" as a site after entering master password, and see if the generated password matches my expectation from previous uses.

**Comment by r2n2** [comment]
[chsm](https://github.com/chsm), that is an outstanding idea!  I won't use 'test'; however, the thought of a code-word to check is intriguing.  Thank you for the idea!

**Comment by chsm** [comment]
I just tend to use "test" because it's quick to type, but I suppose for that matter you could just enter "." instead.

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
