### ISSUE TITLE
v2.5.2 crashes @ launch on iOS 10.1 #system-ios

### ISSUE THREAD

**Issue by yukon-cornelius** [Lyndir/MasterPassword#171]
I get 15 seconds of blank-screen, then returns back to home screen (with app still in background).  To eliminate any compatibility issues, I've done the following ...

- cleared out the app's storage from iCloud (from prior installations)
- closed app, then enabled both "check for inconsistencies" and "send diagnostic info" in Settings
- rebooted device
- removed & reinstalled (still with iCloud cleared out)

... and nothing seems to help.  Is there anything else I can do to help diagnose or make compatible?  Thanks!

**Comment by lhunath** [comment]
Can you have a look at your crash logs?

**Comment by lhunath** [comment]
Alternatively, you can sync with iTunes to find them; eg.
https://help.getpocket.com/article/1098-how-to-find-the-iphone-ipad-app-crash-logs

**Comment by lhunath** [comment]
Is this still an issue?
