### ISSUE TITLE
Custom ciphering function

### ISSUE THREAD

**Issue by alexlawrence** [Lyndir/MasterPassword#177]
(I do not have much experience with MasterPassword so far, so please forgive me if the following suggested feature already exists.)

Is there any possibility to provide a custom ciphering/encryption code function? 

While I like the idea of only remembering one master password, I am a bit worried at the same time. For me personally it would appear a lot securer if I could provide one master password in combination with a custom code function.

For example (pseudo js code):

```javascript
var customCipher = function(parameters) {
  if (parameters.siteName.length % 2 == 0) {
    parameters.masterPassword = parameters.masterPassword.toUpperCase();
  }
  else {
    parameters.masterPassword = parameters.masterPassword.toLowerCase();
  }
}
```

I understand that this would primarily be a feature for developers. However, at some point it would be possible to provide a predefined collection of ciphering functions from which one could be chosen.

**Comment by lhunath** [comment]
Hey alex,

I understand you have worries, but this proposal would needlessly complicate the algorithm and doesn't actually provide any added benefit.  The security of the solution is provided by the strength of the underlying ciphers and security through mathematical certainty is always better than security through obscurity.

I understand that it is non-trivial for non-cryptographic experts to derive a solid feeling of confidence from looking at an algorithm, but that's really where the security is.  I'm not going to support any pointless complication or obfuscation of the algorithm for the sake of satisfying a feeling.
