### ISSUE TITLE
About your branding...

### ISSUE THREAD

**Issue by ikocevski** [Lyndir/MasterPassword#178]
Your app icon is very reminiscent of that of LastPass which I believe is copyrighted. Have you had any problems with this or considered changing it? Just wondering, I was making an icon for the [ICEcons](https://github.com/dkanada/ICEcons) icon pack so I noticed this.

**Comment by lhunath** [comment]
LastPass assumed this icon years after MasterPassword did.

**Comment by lhunath** [comment]
https://blog.lastpass.com/2016/02/meet-the-new-lastpass-logo.html/

The very first version of the MP logo in this style:
https://github.com/Lyndir/MasterPassword/blob/571898632f78551b621adb4116ded6bb7f3285a8/OnePassword/Resources/Icon%402x.png

**Comment by wangkesen** [comment]
“...” is not trademarked and Master Password was created before Lastpass so not much of an issue here.

**Comment by ikocevski** [comment]
Okay, that's awesome!
