### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by haroon-ali** [Lyndir/MasterPassword#179]
Hi,
I found no other way, but I just want to help localize/translate the apps in my native language.
Specially the android, web & desktop java apps.

**Comment by haroon-ali** [comment]
I'm also interested in translating the website if you don't mind.

**Comment by lhunath** [comment]
Unfortunately the Master Password apps currently aren't coded in such a way that would facilitate translation.  This is definitely planned for implementation, though, and I'll keep your suggestion in mind for when the code matures to be internationalized.

**Comment by rolandog** [comment]
I can help with translations to Spanish.

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
