### ISSUE TITLE
Fingerprint Prompt after copying 

### ISSUE THREAD

**Issue by wangkesen** [Lyndir/MasterPassword#180]
Not sure if this is just an issue with iOS 11 as I’m on Dev Beta 2. Just reconstructed the big to make sure it was still occurring . So I copy a password by selecting the account password and that’s fine, but then after pressing the home button to switch to where I want to paste it to prior to pasting master password reprompts again for Touch ID. In the picture attached I’ve just copied a password and for demonstration purposes about to paste it here. As you can see prior to pasting master password is prompting again for the password after already signing in with my Touch ID. ![Reprompt](http://i.imgur.com/qEop46W.jpg)

**Comment by lhunath** [comment]
Interesting.  I daresay this is an iOS security feature that uses the Master Password method of copying your password exactly the way it was intended, making the password only available upon explicit unlocking.

The intention here is to make sure apps cannot read the password out of the pasteboard without your consent, and to ensure that the password isn't saved in memory but rather it is generated only when you actually need it and thrown away again after.

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
