### ISSUE TITLE
Web source code missing

### ISSUE THREAD

**Issue by lightswitch05** [Lyndir/MasterPassword#183]
I'm unable to find the source for https://js.masterpasswordapp.com/. 

At the top of the page there is a dead link here: https://github.com/Lyndir/MasterPassword/tree/master/Site/mpw-js

Also the test suite link fails as well: https://js.masterpasswordapp.com/js/mpw-js/test/

**Comment by lightswitch05** [comment]
I found it here: https://github.com/Lyndir/MasterPassword/tree/master/platform-independent/web-js

But the links should still be updated

**Comment by HorribleGeek** [comment]
@lhunath @Lyndir This has to be updated! It will take just a minute, Please do this asap.

**Comment by lhunath** [comment]
My apologies, this was already resolved in the repo, just not synced out to https://js.masterpasswordapp.com.  Done now.
