### ISSUE TITLE
3rd party scripts should not be allowed within the web app

### ISSUE THREAD

**Issue by lightswitch05** [Lyndir/MasterPassword#184]
The web app relies on 3rd party provided scripts: https://github.com/Lyndir/MasterPassword/blob/master/platform-independent/web-js/index.html#L64

This is a security issue as that 3rd party could be compromised to provide different scripts to capture passwords. jQuery and other script could easily be provided within the confines of masterpasswords own host

**Comment by lightswitch05** [comment]
also: https://github.com/Lyndir/MasterPassword/blob/master/platform-independent/web-js/js/dependencies.js#L19-L23

**Comment by lhunath** [comment]
e91f80d1
