### ISSUE TITLE
Custom counter value for password generation in mobile application

### ISSUE THREAD

**Issue by diabolusss** [Lyndir/MasterPassword#187]
In cli mpw i can assign custom counter value(for example date: 20170724) and if i want to get the same password on phone i must click 20170723 times on counter button which is not i expected. It would be great if someone will change that.

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
