### ISSUE TITLE
validate password in CLI

### ISSUE THREAD

**Issue by vitiral** [Lyndir/MasterPassword#188]
@lhunath commented in #169 that:

> The Java application also supports storing your user and key ID in an mpsites file, and checks the entered master password against it when logging back in later - it should detect typo's and error during the login step (assuming you aren't using the incognito mode).

I would really like this functionality in the CLI as well. This is the major issue that prevents me from using this app (which I love btw!)

**Comment by lhunath** [comment]
The CLI now uses mpsites files as well.  It uses the configuration in mpsites as the defaults for each site and checks your master password against it.  It does not yet write to or update the mpsites file.  For now, this is in master only (not yet released).

**Comment by vitiral** [comment]
Sounds awesome! Is the the `cli-c` or a different one? Really looking forward to it.

Not sure if this is a bug or just my own stupididy, but I can't seem to build cli-c anymore on 03080b9c:
```
# cd MasterPassword/platform-independent/cli-c
# ./build 
Will build targets: mpw...

Building target: mpw...
In file included from core/mpw-marshall-util.c:21:0:
core/mpw-marshall-util.h:23:10: fatal error: json-c/json.h: No such file or directory
 #include <json-c/json.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
```

I'm running Arch Linux and do have `openssl` package installed (which should include dev libs by default).

**Comment by lhunath** [comment]
Yes, that's the one.  It now also depends on the json-c library.

**Comment by lhunath** [comment]
I suggest you pull before trying again.

**Comment by vitiral** [comment]
thanks. Installing `json-c` did the trick

**Comment by vitiral** [comment]
I can't seem to find any documentation on how to create the mpsites file with the password to check. How do I do that? Is there a template I can use? Where would I put the template?

Thanks!

**Comment by lhunath** [comment]
The template for the current format is in #164 - but presumably, the easiest way of creating the file is by creating a user in the iOS/macOS/Java app and exporting it.
