### ISSUE TITLE
signing and Manifest issue

### ISSUE THREAD

**Issue by IzzySoft** [Lyndir/MasterPassword#189]
At least for the last `.apk`, APKSigner reports an issue:

    WARNING: META-INF/INDEX.LIST not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
    WARNING: META-INF/LICENSE not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.

Apart from that, according to `aapt d badging` the Manifest seems to lack any application label entry – so the app has no "name" (apart from its package name). A look at the Manifest here in the repo seems to confirm this.

Just to let you know – and in the hope to have it fixed, of course :wink:

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.

**Comment by IzzySoft** [comment]
Thanks for the pointer! Metadata updated.

Btw: You know that GitLab is hosted by MS (and sponsored a.o. by Google)? I'll move my repos somewhere else as well, as soon as I've found a fitting place.
