### ISSUE TITLE
Scripting: allow for password to be piped in via stdin

### ISSUE THREAD

**Issue by TerraTech** [Lyndir/MasterPassword#197]
For scripting, I see that 2.6 is a step in the right direction with ```-q``` suppressing the password strength meter - so thanks for that.  :)

What I'd like to have now is the ability to pipe in the password on stdin for script usage:
```bash
$ masterpass=$(echo mysupersecretpassword | mpw -q -u Terra google.com)
or
$ masterpass=$(mpw -q -u Terra google.com <<<"${mypass}")
```
Does this ability already exist, and I'm just missing it?

**Comment by lhunath** [comment]
It depends on how your system implements `getpass(3)`.  Usually, passwords are read directly from the terminal device to enforce that they come directly from the user and not from an unprotected source.

Before deciding on this type of functionality, I would like a more thorough evaluation of both the benefit of this type of request as well as the security implications for using it, in addition to what possible alternative approaches exist that may be better.

**Comment by lhunath** [comment]
I should add that mpw currently has a -M feature which allows passing the master password as an argument, as documented by `mpw -vvh`.  Passing a secret over arguments is highly insecure, though, so this is really exists primarily for testing (eg. `mpw-cli-tests`)

**Comment by lhunath** [comment]
The password can now be supplied via a file descriptor or pipe using `-m <fd>`, as a string using `-M <password>`, entered directly on the terminal when prompted, or by using an askpass program using `MPW_ASKPASS=<program>`, eg. `MPW_ASKPASS='ssh-askpass'`.  The askpass program will also be used for other prompts, such as username or site name if unspecified.

**Comment by TerraTech** [comment]
That will work out nicely, thank you!
