### ISSUE TITLE
Cannot build mpw on Debian

### ISSUE THREAD

**Issue by debiantriage** [Lyndir/MasterPassword#201]
I download masterpassword-cli.tar.gz and ran ./build on Debian stretch and buster.  Below is the output.

Fetching: scrypt, using package...
--2017-09-05 18:18:07--  https://www.tarsnap.com/scrypt/scrypt-1.2.1.tgz
`Resolving www.tarsnap.com (www.tarsnap.com)... 23.21.149.109, 2406:da00:ff00::36e1:d502
Connecting to www.tarsnap.com (www.tarsnap.com)|23.21.149.109|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 127619 (125K) [application/x-gzip]
Saving to: ‘scrypt-1.2.1.tgz’

scrypt-1.2.1.tgz             100%[==============================================>] 124.63K   427KB/s    in 0.3s

2017-09-05 18:18:08 (427 KB/s) - ‘scrypt-1.2.1.tgz’ saved [127619/127619]

Verifying package: ../scrypt-1.2.1.tgz, against digest:4621f5e7da2f802e20850436219370092e9fcda93bd598f6d4236cce33f4c577...Invalid command 'sha'; type "help" for a list.
 mismatch!
Downloaded package doesn't match digest.

The build script has the line

openssl sha -sha256 -binary < "$1" | od -t x1 -An -v | tr -d '[:space:]'

Debian's openssl does not have "sha" as a Message Digest command, so I used sha256 instead of it. The compilation then completed successfully.

Cheers,

Brian.

**Comment by lhunath** [comment]
When did you download the tarball?

**Comment by ilpianista** [comment]
I can confirm this is already fixed in 2.6-cli-1.

**Comment by debiantriage** [comment]
Downloaded yesterday using

wget "https://ssl.masterpasswordapp.com/masterpassword-cli.tar.gz"

Cheers,

Brian.

**Comment by ilpianista** [comment]
@debiantriage download it again ;-)

**Comment by lhunath** [comment]
Yeah, I released 2.6-cli-1 yesterday which no longer depends on libscrypt or external dependencies.  Though you'll need libsodium before building, and a few others.  See the `README.md` file included in the new tarball.

**Comment by debiantriage** [comment]
> Yeah, I released 2.6-cli-1 yesterday which no longer depends on libscrypt or external
> dependencies. Though you'll need libsodium before building, and a few others. See the
> README.md file included in the new tarball.

brian@desktop:~$ ls -l build
-rwxr-xr-x 1 brian brian 5626 Sep  4 19:29 build

That's sneaky! I spent all yesterday afternoon trying to sort this out (as well as other problems of my own making). I've a good mind to take my custom to lastpass. :)

Thank you for the continuing work.

Cheers,

Brian.

**Comment by lhunath** [comment]
By the way, as of 2.6, the CLI can also handle custom (hybrid) passwords by saving them in the configuration file (under `~/.mpw.d`).

**Comment by debiantriage** [comment]
Good to know. I am a novice mpw user but am already captivated by the simplicity of the cli interface. My intention is to integrate it with the dialog utility. Lots of hours of fun (as long as its developer doesn't pull the rug from under my feet :) ).

I appreciated being pointed in the right direction, so thanks again.

Regards,

Brian.

**Comment by lhunath** [comment]
Good luck.  Note that for password input, 2.6 supports askpass (`MPW_ASKPASS`), which will likely be better (safer) than using dialog for juggling the master password.
