### ISSUE TITLE
./install as root only alters /root/.bashrc

### ISSUE THREAD

**Issue by debiantriage** [Lyndir/MasterPassword#205]
On Debian ./install as a user quite rightly informs that /usr/local/bin is not writable. The script then terminates. ./install with root priviilege installs mpw and alters root's .bashrc. I'd suggest the second action should alter a user's .bashrc.

Regards,

Brian.

**Comment by debiantriage** [comment]
I forget to mention that this was for system-c.

-- 
Brian

**Comment by lhunath** [comment]
I'm not sure I want to try to make `install` "smart" like this.  When running as root, there is no real indication of what `.bashrc` should really be modified, except for perhaps looking at `SUDO_USER`, which is a hack and certainly won't always be set or point reliably to the right user.

If you want to be installing binaries system-wide, you really shouldn't be using `install`, and neither should you be doing this at the same time as also modifying only a single arbitrary user's `.bashrc` accordingly.

Make a `~/.bin` and let it install there, or install `mpw` at a system level yourself, or using your OS' package manager.

**Comment by debiantriage** [comment]
> If you want to be installing binaries system-wide, you really shouldn't be using install...

I agree with most of what you say but not with this. Your script actually installs mpw to /usr/local/bin. which is the right place for it. What it does not do is provide a usable ~/.bashrc for a user (apart from root). On that level it is useless. I would not envisage or push for any effort being undertaken to make ./install modify a user's ~/.bashrc.

I'd suggest this is a documentation issue. By all means provide advice on the benefits of the additions to ~/.bashrc, but leave it up to user to choose whether to follow it. I actually just copied and pasted what the install script has.

Cheers,

Brian.
