### ISSUE TITLE
'mpw -t p' produces a PIN.

### ISSUE THREAD

**Issue by debiantriage** [Lyndir/MasterPassword#206]
```
brian@desktop:~$ mpw -t p
Your full name: 123
Your master password: 
Site name: 12345
123's password for 12345:
[ ╔▒═☣ ]: 9603
```

'mpw -t phrase' or ' mpw -t ph' produce the expected outcome.

Regards,

Brian.

**Comment by debiantriage** [comment]
Another oddity:

```
brian@desktop:~$ mpw -t ph
Your full name: qwerty
Your master password: 
Site name: ebay
qwerty's password for ebay:
[ ╰▒═☏ ]: lurb zoh bolbuze pay

brian@desktop:~$ mpw
Your full name: qwerty
Your master password: 
Site name: ebay
qwerty's password for ebay:
[ ╰▒═☏ ]: lurb zoh bolbuze pay
```
Shouldn't the second command be using the "long" template? If I specify it explicitly I get back to normal.

```
brian@desktop:~$ 
brian@desktop:~$ 
brian@desktop:~$ mpw -t long
Your full name: qwerty
Your master password: 
Site name: ebay
qwerty's password for ebay:
[ ╰▒═☏ ]: Lure6#CogbYoby
brian@desktop:~$ 
brian@desktop:~$ mpw
Your full name: qwerty
Your master password: 
Site name: ebay
qwerty's password for ebay:
[ ╰▒═☏ ]: Lure6#CogbYoby
```

Regards,

Brian.

**Comment by debiantriage** [comment]
It is only the appearence of normality. For the penultimate command I used the maximum template. This sticks for the 'mpw' command.

```
brian@desktop:~$ mpw -t max
Your full name: 123
Your master password: 
Site name: 12345
123's password for 12345:
[ ╔▒═☣ ]: jfG)U(dSYmLeNkdYgC5'
brian@desktop:~$ 
brian@desktop:~$ mpw
Your full name: 123
Your master password: 
Site name: 12345
123's password for 12345:
[ ╔▒═☣ ]: jfG)U(dSYmLeNkdYgC5'
```

Regards,

Brian.

**Comment by lhunath** [comment]
`mpw` remembers your site settings in `~/.mpw.d/<user name>.mpsites.json`

**Comment by debiantriage** [comment]
Indeed. Thanks for pointer and sorry for the noise.

Except, as 'mpw -h' says
```
-t pw-type i, pin
-t pw-type p,phrase
```

so

```
mpw -t p
```

is not unique and matches the "p" in "pin" and "phrase".

Cheers,

Brian.

**Comment by lhunath** [comment]
The single-letter argument is different from the word-argument.  The single-letter argument is a direct mapping from a type to a letter that represents the type.  The word-argument is just a closest-match test between the argument and the start of the type name.

It's safest to use the single-letter mode, since that's hard-coded.  The word mode is handy if you're going to spell the whole type out, eg. in a script, to document your command better.

**Comment by debiantriage** [comment]
Thank you for the attention to detail. Normally I use word mode but, this time, I was experimenting,

Cheers,

Brian.
