### ISSUE TITLE
mpw -t K (or -t key) error

### ISSUE THREAD

**Issue by TerraTech** [Lyndir/MasterPassword#207]
mpw version: 2.6-cli-2

While looking at the new ```-t K```, ```-t key```, I am running into an error.  Note, I get same error if I use ```-t key```.
```sh
$ ./mpw -F none -t key -P 256 -v
Your full name: foo
Your master password:
Site name: baz
Couldn't open configuration file:
  /home/xxx/.mpw.d/foo.(null): No such file or directory
-----------------
fullName         : foo
identicon        : ■░■■
sitesFormat      : none (fixed)
sitesPath        : (null)
siteName         : baz
siteCounter      : 1
resultType       : key (4160)
resultParam      : 256
keyPurpose       : authentication (0)
keyContext       : (null)
algorithmVersion : 3
-----------------

foo's password for baz:
[ ■░■■ ]: Could not derive result key: Invalid argument
Couldn't generate site result.
```
Please look at this code review comment for the '-t K' option handling: https://github.com/Lyndir/MasterPassword/commit/4f7c28563d951147e5e40ead5c26f1440b95211f#diff-513380837492c47f87789f304a081243R54
I manually patched it to use 'K', but that did not resolve the error.

Am I misusing this new feature and not specifying ```-P``` correctly?  The help output is a bit confusing in regards to the correlation between ```-t K, -P```.  Also ```-s``` appears to be an invalid switch.  I did look at ```mpw-cli-tests``` for guidance, but it hasn't been added yet.

Can you please show an example usage of how to properly use ```-t K```

As an aside, it would be nice if ```mpw``` had a version ```-V``` switch so we could easily copy-n-paste into issues.

TIA!

**Comment by TerraTech** [comment]
```-s``` disappeared in commit: https://github.com/Lyndir/MasterPassword/commit/856233

**Comment by lhunath** [comment]
e3a7ea57e038fa8165852070d9a1215e8ae83312 and d448099a2de46eb6cd6792c07aa1ddbecc7f14e8

**Comment by lhunath** [comment]
For now, mpw's version is shown in `mpw -h`.
