### ISSUE TITLE
gui-java: application exit clears the clip board

### ISSUE THREAD

**Issue by ewirch** [Lyndir/MasterPassword#208]
While this seems to be a important security feature, it effectively prevents using ENTER to copy the password to clipboard using the keyboard. ENTER also closes the application.

Please either keep the clipboard intact, or provide another way how to copy the password using a keyboard shortcut.

Environment: Manjaro Linux, JRE8

**Comment by argo2445** [comment]
I get this issue on Ubuntu Gnome Linux too. 
It could be avoided by typing the password as mentioned in issue #140. 
A check box or something similar could be added to change the submit/ENTER action to ALT+TAB and typing the password. I think it should not be the default behavior but it would be useful.

I tested this on Windows and Linux (GNOME). 

Example using java.awt.Robot: 
```
String text2write = "This is my generated Password";
Robot robot = new Robot();
robot.delay(200);
robot.keyPress(KeyEvent.VK_ALT);
robot.keyPress(KeyEvent.VK_TAB);
robot.delay(200);
robot.keyRelease(KeyEvent.VK_TAB);
robot.keyRelease(KeyEvent.VK_ALT);
robot.delay(300);

for (char c : text2write.toCharArray()) {
	int keyCode = KeyEvent.getExtendedKeyCodeForChar(c);
	if (KeyEvent.CHAR_UNDEFINED == keyCode) {
		throw new RuntimeException("No Key code found for Char '" + c + "'");
	}
	robot.keyPress(keyCode);
	robot.delay(100);
	robot.keyRelease(keyCode);
	robot.delay(100);
}
```

**Comment by lhunath** [comment]
#139

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
