### ISSUE TITLE
platform-independent/cli-c: gcc: error: core/mpw-marshall.c: No such file or directory

### ISSUE THREAD

**Issue by monotykamary** [Lyndir/MasterPassword#209]
Builds after commit [`47164c7a`](https://github.com/Lyndir/MasterPassword/commit/47164c7a92222b849fcac41748d325cdfe8ebe4f) results in a gcc error:

```
Current mpw source version 2.6-cli-2-21-g6e228999...

Building target: mpw...
INFO:     Enabled mpw_sodium (libsodium).
INFO:     Enabled mpw_color (libcurses).
INFO:     Enabled mpw_json (libjson-c).
gcc: error: core/mpw-marshall.c: No such file or directory
```
This is because the actual file is spelled `mpw-marshal.c` instead of `mpw-marshall.c`

**Comment by monotykamary** [comment]
As of commit [`e8187134`](https://github.com/Lyndir/MasterPassword/commit/e818713484270a06bca26acf989395a3b6111cfa):

```
gcc: error: core/mpw-marshal-util.c: No such file or directory
```
This is because the actual file is spelled `mpw-marshall-util.c` instead of `mpw-marshal-util.c`. I feel like the word itself is evil.

**Comment by lhunath** [comment]
34540f084482cdd5e5c819a6dfdd35bdadd65940
