### ISSUE TITLE
Suggestion: sign binaries, publish sha256 hashes

### ISSUE THREAD

**Issue by rolandog** [Lyndir/MasterPassword#210]
Maybe this is an issue that might be tied to #189, but I would think that the availability of sha256 hashes and binaries that are signed should be considered, given the nature of what MasterPasswordApp handles.

I would point to [Vagrant's security page](https://www.hashicorp.com/security/) for a showcase on good practices. Though there are many others that come to mind.

**Comment by lhunath** [comment]
The APK is signed and the standard C archives are too (https://ssl.masterpasswordapp.com/masterpassword-cli.tar.gz.sig).  Furthermore, each major release tag is GPG signed in GIT.

I'm certainly open to suggestions and improvements.

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
