### ISSUE TITLE
Segfault from mpw_strdup on arch linux

### ISSUE THREAD

**Issue by kevinkjt2000** [Lyndir/MasterPassword#212]
I tried compiling from master today and was greeted with segfaults.  I'm not sure if it is with the version of libc or the newly added mpw_strdup.  The test script mpw-cli-tests passed all tests.

```
$ gdb ./mpw
(gdb) run
Starting program: /home/ktindall/builds/MasterPassword/platform-independent/cli-c/mpw
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Your full name: lalala
Your master password: asdfasdf

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7493247 in __strlen_avx2 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7493247 in __strlen_avx2 () from /usr/lib/libc.so.6
#1  0x000055555555c61e in mpw_strdup ()
#2  0x000055555555ff29 in mpw_getpass ()
#3  0x0000555555560eed in cli_masterPassword ()
#4  0x00005555555564f1 in main ()
```

```
$ pacman -Q glibc
glibc 2.26-4
```

**Comment by lhunath** [comment]
Do you still have this problem?

**Comment by kevinkjt2000** [comment]
Assuming this comment means there were some changes?  Let me pull and try again.

**Comment by kevinkjt2000** [comment]
Well it didn't crash, but wowowowowow... what is this new sleek interface?!  It's awesome and doesn't save anything to my tmux scrollback.  Consider this closed and me impressed at the same time.
