### ISSUE TITLE
No GeneratedName option for Android app

### ISSUE THREAD

**Issue by Briscoooe** [Lyndir/MasterPassword#218]
There is no option to generate a username on the Android app. There is an optional "Login" value to be generated but it does not use the same algorithm for "Name" generation that the web app or desktop app uses.

Could I submit a pull request for this feature if I were to complete it?

**Comment by patrikr** [comment]
Sounds like you're talking about the devland app, if so you're in the wrong place on github. Try here: https://github.com/dkunzler/masterpassword

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
