### ISSUE TITLE
MasterPassword vulnerable to keyloggers. Solution: smartcards

### ISSUE THREAD

**Issue by gabridome** [Lyndir/MasterPassword#220]
I'm not a security expert and my idea may sound a bit naive but MHO Nowadays, relaying on a master secure password is no longer the case.

The alternative is available today and relays on asymmetric cryptography and smartcards:
Digital Signing can be used as a better authentication means because the key is secured at least from keyloggers.

Even without using gpg, evidently impratical, a system based on U2F could be a good integration with at least three device configured as a convenient backup.

From a user standpoint yubikey, Ledger, trezor and any capable U2F device could be good candidates for an upgrade for a good deterministic password manager.
The weak point here is a good architecture to protect the key registration phase. 

For mobile use we should wait for a good NFC or BLE implementation.

**Comment by lhunath** [comment]
Please note that Master Password does not perform authentication and furthermore aims to free you from hardware dependency.

Smartcards, digital signatures, two-factor authentication and all similar systems are authentication systems, they have a value, but they cannot really contribute anything to Master Password.  If supported by the site, they can be used for direct authentication as an alternative to Master Password.

If you feel there is any contribution that could be made to Master Password, feel free to go in depth.

> MHO Nowadays, relaying on a master secure password is no longer the case.
I'm not sure what this means.
