### ISSUE TITLE
Crashing trying to login

### ISSUE THREAD

**Issue by Johnny-Mavric** [Lyndir/MasterPassword#221]
I'm trying to login into the app on ios and it keeps crashing. Whether it be my master password or touch id it keeps crashing. I can't access any of my passwords. On ios 10.3.2.

**Comment by Raviu8** [comment]
I suffer the same problem with .jar file on windows. I've to manually kill it one or two time using task manager before it works fine.

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
