### ISSUE TITLE
Question / help

### ISSUE THREAD

**Issue by damko** [Lyndir/MasterPassword#222]
How can I run just the mpw binary (the core I mean) on android (arm64) from terminal? I'm lost.

**Comment by lhunath** [comment]
The CLI app has not yet been tested for compilation on ARM64, but feel free to try it if you can get an ARM64 toolchain going.  The process is essentially just, run the `./build` script or the `cmake` script.  We do not distribute any binaries for the CLI app, arm64 or other.
