### ISSUE TITLE
How to use offline in ChromeOS?

### ISSUE THREAD

**Issue by git-sgmoore** [Lyndir/MasterPassword#224]
Has anyone used this successfully on ChromeOS locally?

**Comment by git-sgmoore** [comment]
I tried running the index.html in web-js while on airplane mode. I could fill in name and master password, but it wouldn't go beyond that.

**Comment by lhunath** [comment]
You'll need to make sure to check out the full tree and submodules at:
https://github.com/Lyndir/MasterPassword/tree/master/platform-independent/web-js

At that point, it should work completely independently.
