### ISSUE TITLE
Android Login Name Not The Same As Cli

### ISSUE THREAD

**Issue by wixregiga** [Lyndir/MasterPassword#225]
The command line generates a different login name than android  

`mpw -u "My Name" -t b -p i "site.com"`

I am running it via Docker using the image: cbuctok/masterpassword 

`docker run -it --rm cbuctok/masterpassword mpw -u "YOUR_NAME" -p i "SITENAME.COM"`

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
