### ISSUE TITLE
Running Master Password on NodeMCU microcontroller 

### ISSUE THREAD

**Issue by wuhanstudio** [Lyndir/MasterPassword#226]
I've managed to serve **Master Password** on a 32bit microcontroller. I'm using **mpw-js** for now and my passwords have been correctly generated. But is it possible to run as native C code on a 32bit microcotroller with 50K RAM and 1MB flash?

Thank you very much.

Project link :

    https://github.com/wuhanstudio/masterpassword-nodemcu

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
