### ISSUE TITLE
Remove nix from topics

### ISSUE THREAD

**Issue by Infinisil** [Lyndir/MasterPassword#227]
Currently this repository includes "nix" in its topic list, probably wanting to refer to linux. The topic "nix" however belongs to a package manager and language (see https://nixos.org/nix/) not having anything to do with this repository and should therefore be removed.

I noticed this because this repository is currently [the third most starred one in the nix topic](https://github.com/topics/nix)

**Comment by lhunath** [comment]
Presumably the intent was to add `*nix` as a platform topic.  I've removed it now.
