### ISSUE TITLE
Password leak on website due to not clearing value of sitePassword's childNode's textContent

### ISSUE THREAD

**Issue by rolandog** [Lyndir/MasterPassword#232]
This leak happens on [js.masterpasswordapp.com](https://js.masterpasswordapp.com/). This could happen on a shared computer, or on an 'Evil Maid' scenario.

Here is a screenshot of the result of having a user, `asdf`, with password, `asdf`, type in `asdf`:
![js-masterpasswordapp-com_asdf-asdf-asdf](https://user-images.githubusercontent.com/12400926/37839663-97cd866c-2e80-11e8-9de7-e9a02fdec641.png)

After clicking the sign-out button, but not closing the tab or window, user `zxcv` with password `zxcv` decides to sign in, but to his surprise, he would be greeted with the previous user's last password in the `sitePassword` element's text chidlNode's textContent:
![js-masterpasswordapp-com_zxcv-zxcv](https://user-images.githubusercontent.com/12400926/37840023-9dda857c-2e81-11e8-9987-ad79483529a3.png)

Useful counter-measures:
- Type in something randomly before signing out, if you plan on not closing the window or tab.
- Close the window or tab

Granted, there might be higher risks (like a keylogger) when using a shared computer. But this at least makes sure that your password is safe in this unlikely - yet plausible - scenario.

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
