### ISSUE TITLE
Ssl on masterpasswordapp.com

### ISSUE THREAD

**Issue by jeremiahogutu** [Lyndir/MasterPassword#233]
I'm just curious as to why masterpasswordapp website is not using a https connection by default?

**Comment by lhunath** [comment]
Mainly for economic reasons, it's served from S3 and it's a read-only site (you don't send any information to it).  I'm not opposed to going SSL-first/only, but I'd need a method of doing that which is economically viable.

**Comment by w4vz** [comment]
Can’t you use Let’s Encrypt, its free ?

**Comment by lhunath** [comment]
I do use Let's Encrypt.  However, S3 (AFAIK) doesn't provide an SSL endpoint.

**Comment by w4vz** [comment]
damn that’s a bummer.

Not sure why you need it for but I use vultr.com for my hosting needs. maybe you can look into it ? starts at $2.50 per month for vm with full shell access. might be enough ?

**Comment by jedevc** [comment]
A possibility that I just thought of would be to host the app on github pages. To my understanding, they provide HTTPS out of the box. To set it up, all you'd need would be a separate gh-pages branch containing the files you'd want to serve.

**Comment by lhunath** [comment]
Dup #238

**Comment by lhunath** [comment]
SSL enabled through Cloudflare.
