### ISSUE TITLE
Disable stroring site data in .mpw.d

### ISSUE THREAD

**Issue by vindex10** [Lyndir/MasterPassword#234]
Hello! For me it is an additional security feature to have specific counter, name and sitename per site. It will not change a lot if someone will try to crack me, but still I wouldn't like to have settings stored and make the cracking process simpler :). Here I'm publishing a patch to disable the wraning:

```diff
diff --git a/cli/mpw-cli.c b/cli/mpw-cli.c
index e980cae..51ccec5 100644
--- a/cli/mpw-cli.c
+++ b/cli/mpw-cli.c
@@ -465,7 +465,7 @@ void cli_user(Arguments *args, Operation *operation) {
     }
 
     // Load the user object from mpsites.
-    if (!sitesFile)
+    if (true || !sitesFile)
         mpw_free_string( &operation->sitesPath );
 
     else {
@@ -760,7 +760,7 @@ void cli_mpw(Arguments *args, Operation *operation) {
 
 void cli_save(Arguments __unused *args, Operation *operation) {
 
-    if (operation->sitesFormat == MPMarshalFormatNone)
+    if (true || operation->sitesFormat == MPMarshalFormatNone)
         return;
 
     if (!operation->sitesFormatFixed)
```

Apply it with `patch -p1`. Or just make changes by hand.

Upd.

Checked on `master`. Error message is off now and ~/.mpw.d being created automatically now, but still I couldn't find the way to disable storing data. It would be great to have a kind of flag for that.

**Comment by lhunath** [comment]
This should already be possible using `-Fn`.

**Comment by vindex10** [comment]
Thanks! It works.
