### ISSUE TITLE
Homepage doesn't default to HTTPS

### ISSUE THREAD

**Issue by TimDG** [Lyndir/MasterPassword#238]
Nowadays, not using HTTPS by default is a bad idea, especially for a security application. Please make sure that your entire site defaults to HTTPS using the correct security headers (at the very least HSTS).

**Comment by jedevc** [comment]
This issue has been raised before in #233.

Although no sensitive data passes between the server and the client, in theory, without HTTPS, an attacker might be able to inject their own code into the client which would allow them to steal passwords.
