### ISSUE TITLE
Homepage link points to page with invalid certificate

### ISSUE THREAD

**Issue by TimDG** [Lyndir/MasterPassword#239]
The "Needs Contributor" issues link on your homepage points to https://project.lyndir.com/youtrack/issues?q=%23%7BNeeds%20Contributor%7D

However, this page displays a certificate warning: 
![image](https://user-images.githubusercontent.com/1313186/38794794-8a6e6c5a-4156-11e8-862d-80d2281393a4.png)

The reason for this is because the hostname doesn't match the one on the certificate:
![image](https://user-images.githubusercontent.com/1313186/38794765-6c568c5c-4156-11e8-857b-736e90823751.png)

**Comment by lhunath** [comment]
project.lyndir.com is no longer in use and was migrated to github.  Link removed.  Thanks.
