### ISSUE TITLE
Is it possible to disable the ncurses password ask?

### ISSUE THREAD

**Issue by zetaomegagon** [Lyndir/MasterPassword#240]
Hello,

I use the cli version. I used to just type my master password into a blank terminal prompt, sudo style. With the latest pull I now get an ncurses "pop-up" asking for my master password. This screws with my custom mpw function (for gpaste-client) and is distracting for me. Is there a way to disable this?
- I have not tried disabling icon colorizing because that is a feature to me.
- `echo $MPW_ASK_PASS` returns nothing
- `uname -r`: **4.15.17-300.fc27.x86_64**

Thanks!

![screenshot from 2018-04-19 17-22-47](https://user-images.githubusercontent.com/24728279/39019147-56635964-43f6-11e8-8878-475c159588b9.png)

**Comment by lhunath** [comment]
This interface was introduced to assist with a cross-platform secure password input.

If you don't like it, there are a few options:
1. Disable color / ncurses.
2. See `mpw -h` for the `-m` option.
3. Use an `askpass` program by setting the environment variable `MPW_ASKPASS`.

If you're using `mpw` from a script, you'll probably want to consider `-m`.  The askpass approach allows you to define a program that will read the password and send it to `mpw`.  `ssh-askpass` can be used, or any graphical equivalent.  You could even make your own.  The simplest askpass program that would emulate what we had before through a bash script, would be something like:

    #!/usr/bin/env bash
    read -srp "$1" && echo "$REPLY"

**Comment by zetaomegagon** [comment]
Ok, cool. I can work with that.

I did notice, however, when I built without color support the my master password is visible when typing it in. I used this as per the readme:

`cmake -DUSE_COLOR=OFF . && make`

Just thought you'd want to know.

![screenshot from 2018-04-19 17-41-28](https://user-images.githubusercontent.com/24728279/39019923-f268197e-43f8-11e8-88ae-58b7247a96a3.png)
