### ISSUE TITLE
Error on xcode build

### ISSUE THREAD

**Issue by pdp2015** [Lyndir/MasterPassword#241]
Hi, i have tried to build the app in xcode (platform- darwin, MasterPassword.xcworkspace)

But i get 2 errors (build failed):

Scripts/build_libjson-c-ios: line 4: hash: automake: not found
Missing automake.
Command Scripts/build_libjson-c-ios failed with exit code 1

Scripts/build_libsodium-ios: line 4: hash: automake: not found
Missing automake.
Command Scripts/build_libsodium-ios failed with exit code 1

Any ideas whats causing this?

Many Thanks

**Comment by lhunath** [comment]
Yes, you're missing automake.

You need automake, autoconf and libtool.  You can use homebrew to install them, or do so manually.
