### ISSUE TITLE
Java GUI update check failing

### ISSUE THREAD

**Issue by lhunath** [Lyndir/MasterPassword#242]
Looks like the Java GUI's update check is failing as a result of Java not following HTTP redirects which are currently sent from http -> https by CloudFlare.

**Comment by lhunath** [comment]
Temporarily addressed by disabling the HTTP -> HTTPS redirect.

**Comment by 2ajoyce** [comment]
My complaint initiated this.  I feel so important!

**Comment by lhunath** [comment]
Thanks, @2ajoyce.  Complaints++
