### ISSUE TITLE
Logo Design: MasterPassword

### ISSUE THREAD

**Issue by baranpirincal** [Lyndir/MasterPassword#248]
Hello!  I saw that your project has no logo design yet. If you want to, I can contribute on your project with making logo design. I am waiting feedback from you, have a nice day!

Best Regards
Baran Pirinçal
Graphic Designer

**Comment by lhunath** [comment]
The project already has a logo.

https://github.com/Lyndir/MasterPassword/blob/e7a3a2a01dcf4ef982dcdc5d0f9512a0eef3e2aa/img/icon.png
