### ISSUE TITLE
Special symbols too exotic

### ISSUE THREAD

**Issue by xeruf** [Lyndir/MasterPassword#258]
The default long pattern has different types of brackets and braces, which some sites like https://mein.finanzen-zero.net/depot-eroeffnen/registrieren don't like - not sure what to choose now to stay safe ^^
<img width="417" alt="image" src="https://user-images.githubusercontent.com/13354331/219055875-f4c233e3-be3b-4f4d-b5b9-aaac09e450bb.png">

**Comment by lhunath** [comment]
Kindly assist us by posting your finding at: https://chat.spectre.app/d/34-contribute-website-password-policies/4
My recommendation in this scenario is to just increase your site counter to get a new password with a different symbol.

**Comment by xeruf** [comment]
Thank You, forgot about that thread :)
