### ISSUE TITLE
"press [Enter] to copy the password" closes the app

### ISSUE THREAD

**Issue by ghost** [Lyndir/MasterPassword#73]
This is on Windows 7 64bit with Java 1.7.0-17. When I hit enter to copy the password to the clipboard the app shuts down and I have to start it from scratch. Not sure whether it crashes or closes on purpose though. There's no output at all on the console, it looks like a clean shutdown.

In case its intended behaviour please reconsider this. Entering my master password every single time I need a password is more annoying than typing the (shorter) actual passwords off of the app instead of clipboarding it.

**Comment by fallerOfFalls** [comment]
How does one put their password in a config file? What config file? I have a .mpw.d folder that contains a mysites file. Is that what you mean? If so which line do I change and how? Is there any documentation anywhere?
